In [1]:
import pandas as pd
import numpy as np

In [4]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [5]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [112]:
date.head()

,date,date_year,date_month,date_month_name,date_day,date_dow,day_dow_name,date_is_weekend,date_week,date_quater,date_semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,1,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,2,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,1,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,5,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,6,1,1

In [6]:
time.isnull().sum()

date    0
msg     0
dtype: int64

In [7]:
time.shape

(1000, 2)

In [8]:
date.shape

(1000, 4)

In [9]:
date.isnull().sum()

date          0
product_id    0
city_id       0
orders        0
dtype: int64

In [10]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   str
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), str(1)
memory usage: 31.4 KB

In [11]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   str
 1   msg     1000 non-null   str
dtypes: str(2)
memory usage: 15.8 KB

In [13]:
date['date']

0      2019-12-10
1      2018-08-15
2      2018-10-23
3      2019-08-17
4      2019-01-06
          ...
995    2018-10-08
996    2018-12-06
997    2019-05-07
998    2019-03-03
999    2019-10-15
Name: date, Length: 1000, dtype: str

# Working with Dates

In [14]:
# Converting the column date into datetime datatype

date['date'] = pd.to_datetime(date['date'])

In [15]:
date['date'].info()

<class 'pandas.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: date
Non-Null Count  Dtype
--------------  -----
1000 non-null   datetime64[us]
dtypes: datetime64[us](1)
memory usage: 7.9 KB

<h4 style="color:green">1. Extract Year</h4>

In [17]:
date['date_year'] = date['date'].dt.year

In [19]:
date['date_year'].head()

0    2019
1    2018
2    2018
3    2019
4    2019
Name: date_year, dtype: int32


<h4 style="color:green">2. Extract Month</h4>

In [23]:
date['date_month'] = date['date'].dt.month

In [24]:
date['date_month'].head()

0    12
1     8
2    10
3     8
4     1
Name: date_month, dtype: int32

<h4 style="color:green">3. Extract Month Name</h4>

In [28]:
date['date_month_name'] = date['date'].dt.month_name()

In [29]:
date['date_month_name']

0      December
1        August
2       October
3        August
4       January
         ...
995     October
996    December
997         May
998       March
999     October
Name: date_month_name, Length: 1000, dtype: str

In [30]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

<h4 style="color:green">4. Extract Day</h4>

In [31]:
date['date_day'] = date['date'].dt.day

In [32]:
date['date_day']

0      10
1      15
2      23
3      17
4       6
       ..
995     8
996     6
997     7
998     3
999    15
Name: date_day, Length: 1000, dtype: int32

In [33]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

<h4 style="color:green">5. Extract day of week</h4>

In [34]:
date['date_dow'] = date['date'].dt.day_of_week

In [35]:
date['date_dow']

0      1
1      2
2      1
3      5
4      6
      ..
995    0
996    3
997    1
998    6
999    1
Name: date_dow, Length: 1000, dtype: int32

<h4 style="color:green">6. Day of week-name</h4>

In [36]:
date['day_dow_name'] = date['date'].dt.day_name()

In [37]:
date['day_dow_name'].head()

0      Tuesday
1    Wednesday
2      Tuesday
3     Saturday
4       Sunday
Name: day_dow_name, dtype: str

In [ ]:
date.drop(columns=['product_id','city_id','orders'])

In [38]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,day_dow_name
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday

<h4 style="color:green">7. is Weekend on day ?</h4>

In [46]:
date['date_is_weekend'] = np.where(date['day_dow_name'].isin(['Sunday','Saturday']),1,0)

date.head()

,date,date_year,date_month,date_month_name,date_day,date_dow,day_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

<h4 style="color:green">8. Extract week of the year</h4>

In [53]:
date['date_week'] = date['date'].dt.weekday

In [55]:
date.head()

,date,date_year,date_month,date_month_name,date_day,date_dow,day_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,1
1,2018-08-15,2018,8,August,15,2,Wednesday,0,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,1
3,2019-08-17,2019,8,August,17,5,Saturday,1,5
4,2019-01-06,2019,1,January,6,6,Sunday,1,6

<h4 style="color:green">9. Extract Quater</h4>

In [56]:
date['date_quater'] = date['date'].dt.quarter

In [57]:
date.head()

,date,date_year,date_month,date_month_name,date_day,date_dow,day_dow_name,date_is_weekend,date_week,date_quater
0,2019-12-10,2019,12,December,10,1,Tuesday,0,1,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,2,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,1,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,5,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,6,1

<h4 style="color:green">10. Extract Semester</h4>

In [59]:
date['date_semester'] = np.where(date['date_quater'].isin([1,2]),1,2)

date.head()

,date,date_year,date_month,date_month_name,date_day,date_dow,day_dow_name,date_is_weekend,date_week,date_quater,date_semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,1,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,2,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,1,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,5,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,6,1,1

# 2. Extract Time

In [72]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [60]:
import datetime

In [70]:
today = datetime.datetime.today()

today

datetime.datetime(2026, 2, 23, 22, 29, 59, 520756)

In [71]:
today - date['date']

0     2267 days 22:29:59.520756
1     2749 days 22:29:59.520756
2     2680 days 22:29:59.520756
3     2382 days 22:29:59.520756
4     2605 days 22:29:59.520756
                 ...
995   2695 days 22:29:59.520756
996   2636 days 22:29:59.520756
997   2484 days 22:29:59.520756
998   2549 days 22:29:59.520756
999   2323 days 22:29:59.520756
Name: date, Length: 1000, dtype: timedelta64[us]

In [73]:
(today - date['date']).dt.days

0      2267
1      2749
2      2680
3      2382
4      2605
       ...
995    2695
996    2636
997    2484
998    2549
999    2323
Name: date, Length: 1000, dtype: int64

In [74]:
# months passed

In [88]:
np.round((today - date['date']) / np.timedelta64(1, 'W'),0)

0      324.0
1      393.0
2      383.0
3      340.0
4      372.0
       ...
995    385.0
996    377.0
997    355.0
998    364.0
999    332.0
Name: date, Length: 1000, dtype: float64

In [84]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[us]
 1   msg     1000 non-null   str
dtypes: datetime64[us](1), str(1)
memory usage: 15.8 KB

In [85]:
# Converting time to datetime datatype

In [86]:
time['date'] = pd.to_datetime(time['date'])

In [87]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[us]
 1   msg     1000 non-null   str
dtypes: datetime64[us](1), str(1)
memory usage: 15.8 KB

<h4 style="color:green">Extract hour</h4>

In [90]:
time['hour'] = time['date'].dt.hour

In [92]:
time['hour']

0       0
1      23
2       0
3       0
4      23
       ..
995     0
996    23
997    23
998    23
999    23
Name: hour, Length: 1000, dtype: int32

In [93]:
time.head()

                 date                                                msg  hour
0 2013-12-15 00:50:00                           ищу на сегодня мужика 37     0
1 2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826    23
2 2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576     0
3 2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...     0
4 2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше    23

<h4 style="color:green">Extract Minute</h4>

In [95]:
time['min'] = time['date'].dt.minute

In [96]:
time.head()

,date,msg,hour,min
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11

<h4 style="color:green">Extract Second</h4>

In [97]:
time['second'] = time['date'].dt.second

In [98]:
time.head()

,date,msg,hour,min,second
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

<h4 style="color:green">Extract Time Part</h4>

In [99]:
time['time'] = time['date'].dt.time

In [100]:
time.head()

,date,msg,hour,min,second,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

<h4 style="color:green">Extract time-difference</h4>

In [102]:
today - time['date']

0     4453 days 21:39:59.520756
1     4317 days 22:49:59.520756
2     4803 days 22:08:59.520756
3     4105 days 21:58:59.520756
4     4502 days 23:18:59.520756
                 ...
995   5092 days 21:39:59.520756
996   4413 days 23:15:59.520756
997   4878 days 22:52:59.520756
998   4994 days 22:55:59.520756
999   4266 days 23:04:59.520756
Name: date, Length: 1000, dtype: timedelta64[us]

<h4 style="color:green">in Second</h4>

In [103]:
(today - time['date']) / np.timedelta64(1,'s')

0      3.848172e+08
1      3.730710e+08
2      4.150589e+08
3      3.547511e+08
4      3.890567e+08
           ...
995    4.400268e+08
996    3.813670e+08
997    4.215416e+08
998    4.315642e+08
999    3.686655e+08
Name: date, Length: 1000, dtype: float64

<h4 style="color:green">in minute</h4>

In [105]:
(today - time['date']) / np.timedelta64(1,'m')

0      6.413620e+06
1      6.217850e+06
2      6.917649e+06
3      5.912519e+06
4      6.484279e+06
           ...
995    7.333780e+06
996    6.356116e+06
997    7.025693e+06
998    7.192736e+06
999    6.144425e+06
Name: date, Length: 1000, dtype: float64

<h4 style="color:green">Extract Hour</h4>

In [106]:
(today - time['date']) / np.timedelta64(1,'h')

0      106893.666534
1      103630.833200
2      115294.149867
3       98541.983200
4      108071.316534
           ...
995    122229.666534
996    105935.266534
997    117094.883200
998    119878.933200
999    102407.083200
Name: date, Length: 1000, dtype: float64

In [111]:
(today - time['date']) / np.timedelta64(1,'ns')

0      3.848172e+17
1      3.730710e+17
2      4.150589e+17
3      3.547511e+17
4      3.890567e+17
           ...
995    4.400268e+17
996    3.813670e+17
997    4.215416e+17
998    4.315642e+17
999    3.686655e+17
Name: date, Length: 1000, dtype: float64